# Repository settings for Ukrainian Voice Transcriber
# This file configures repository settings via the GitHub Settings app
# https://github.com/apps/settings

# Repository basic settings
repository:
  # Basic repository information
  name: ukrainian-voice-transcriber
  description: "🎯 Single-binary Ukrainian video-to-text transcription using Google Cloud Speech-to-Text API"
  homepage: "https://github.com/idvoretskyi/ukrainian-voice-transcriber"
  topics:
    - ukrainian
    - speech-to-text
    - transcription
    - golang
    - google-cloud
    - video-processing
    - audio-processing
    - ffmpeg
    - cli-tool
    - machine-learning

  # Repository visibility and features
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_pages: false
  has_downloads: true
  default_branch: main

  # Repository permissions
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_auto_merge: true
  delete_branch_on_merge: true
  allow_update_branch: true

  # Advanced settings
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Issue and PR templates
labels:
  # Bug labels
  - name: bug
    color: 'd73a4a'
    description: 'Something is not working'
  - name: critical
    color: 'b60205'
    description: 'Critical issue requiring immediate attention'
  - name: security
    color: 'ff6b6b'
    description: 'Security-related issue'

  # Feature labels
  - name: enhancement
    color: 'a2eeef'
    description: 'New feature or request'
  - name: feature
    color: '0052cc'
    description: 'New feature implementation'
  - name: improvement
    color: '5ebeff'
    description: 'Enhancement to existing feature'

  # Documentation labels
  - name: documentation
    color: '0075ca'
    description: 'Improvements or additions to documentation'
  - name: docs
    color: '0e8a16'
    description: 'Documentation updates'

  # Development labels
  - name: dependencies
    color: '0366d6'
    description: 'Pull requests that update a dependency file'
  - name: ci/cd
    color: '1d76db'
    description: 'Continuous integration and deployment'
  - name: testing
    color: '7057ff'
    description: 'Related to testing'
  - name: performance
    color: 'fbca04'
    description: 'Performance improvements'
  - name: refactoring
    color: 'f9d0c4'
    description: 'Code refactoring'

  # Help and support labels
  - name: help wanted
    color: '008672'
    description: 'Extra attention is needed'
  - name: good first issue
    color: '7057ff'
    description: 'Good for newcomers'
  - name: question
    color: 'd876e3'
    description: 'Further information is requested'

  # Status labels
  - name: wontfix
    color: 'ffffff'
    description: 'This will not be worked on'
  - name: duplicate
    color: 'cfd3d7'
    description: 'This issue or pull request already exists'
  - name: invalid
    color: 'e4e669'
    description: 'This does not seem right'
  - name: stale
    color: 'fef2c0'
    description: 'Issue or PR has become stale'

  # Priority labels
  - name: priority/high
    color: 'b60205'
    description: 'High priority issue'
  - name: priority/medium
    color: 'fbca04'
    description: 'Medium priority issue'
  - name: priority/low
    color: '0e8a16'
    description: 'Low priority issue'

  # Component labels
  - name: component/cli
    color: '1f77b4'
    description: 'Related to command-line interface'
  - name: component/auth
    color: 'ff7f0e'
    description: 'Related to authentication'
  - name: component/transcription
    color: '2ca02c'
    description: 'Related to transcription functionality'
  - name: component/build
    color: 'd62728'
    description: 'Related to build system'
  - name: component/docker
    color: '0066cc'
    description: 'Related to Docker/containerization'

# Branch protection rules
branches:
  - name: main
    protection:
      # Require pull request reviews before merging
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: false

      # Require status checks to pass before merging
      required_status_checks:
        strict: true
        contexts:
          - "test"
          - "lint"
          - "build"
          - "security"
          - "dependency-check"
          - "security-scan"

      # Restrict pushes to matching branches
      enforce_admins: false
      allow_force_pushes: false
      allow_deletions: false
      block_creations: false

      # Require conversation resolution before merging
      required_conversation_resolution: true

      # Require linear history
      required_linear_history: false

      # Allow fork syncing
      allow_fork_syncing: true

      # Lock branch (prevent any changes)
      lock_branch: false

# Collaborators and teams (if applicable)
# collaborators:
#   - username: collaborator-username
#     permission: push

# teams:
#   - name: developers
#     permission: push
#   - name: maintainers
#     permission: admin

# Milestones
milestones:
  - title: "v1.0.0 - Initial Release"
    description: "First stable release with core transcription functionality"
    state: open
  - title: "v1.1.0 - Enhanced Features"
    description: "Batch processing, improved error handling, and user experience improvements"
    state: open
  - title: "v2.0.0 - Major Update"
    description: "Advanced features, multiple language support, and performance optimizations"
    state: open

# Repository environments (for deployments)
environments:
  - name: production
    wait_timer: 0
    reviewers: []
    deployment_branch_policy:
      protected_branches: true
      custom_branch_policies: false
    variables:
      - name: ENVIRONMENT
        value: production
    secrets: []

  - name: staging
    wait_timer: 0
    reviewers: []
    deployment_branch_policy:
      protected_branches: false
      custom_branch_policies: true
      custom_branches:
        - main
        - develop
    variables:
      - name: ENVIRONMENT
        value: staging
    secrets: []

# Security settings
security:
  # Enable security advisories
  enable_security_advisories: true
  
  # Enable dependency graph
  enable_dependency_graph: true
  
  # Enable Dependabot security updates
  enable_dependabot_security_updates: true
  
  # Enable Dependabot version updates
  enable_dependabot_version_updates: true

# Pages settings (if using GitHub Pages)
# pages:
#   source:
#     branch: gh-pages
#     path: /
#   cname: your-domain.com