name: ✨ Feature Request
description: Suggest a new feature for Ukrainian Voice Transcriber
title: "[Feature]: "
labels: ["enhancement"]
assignees: ["idvoretskyi"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details about what you'd like to see added.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see
      placeholder: What feature would you like to see added?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you want this feature? What problem does it solve?
      placeholder: |
        What's the use case? What problem are you trying to solve?
        How would this feature benefit you and other users?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Describe your ideal solution. How should this feature work?
        What would the user interface look like?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Are there any alternative solutions or workarounds?
      placeholder: |
        Have you considered any alternative approaches?
        Are there existing workarounds you're using?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Would be helpful"
        - "High - Really need this"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - "Simple - Minor change"
        - "Medium - Moderate development"
        - "Complex - Major feature"
        - "Unknown - Not sure"
      default: 3

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, screenshots, or references
      placeholder: |
        - Screenshots or mockups
        - Links to similar features in other tools
        - Any other relevant information

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: This feature aligns with the project's goals
          required: true
        - label: I am willing to help test this feature when implemented
          required: false