name: ❓ Question
description: Ask a question about Ukrainian Voice Transcriber
title: "[Question]: "
labels: ["question"]
assignees: ["idvoretskyi"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about Ukrainian Voice Transcriber? We're here to help!
        
        Before asking, please check:
        - [README.md](../README.md) for basic usage
        - [User Manual (English)](../docs/USER_MANUAL_EN.md)
        - [User Manual (Ukrainian)](../docs/USER_MANUAL_UK.md)
        - [Existing issues](../issues) for similar questions

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please describe your question clearly
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What category does your question fall into?
      options:
        - "Installation and Setup"
        - "Usage and Features"
        - "Authentication and Configuration"
        - "Troubleshooting"
        - "Performance and Optimization"
        - "Contributing and Development"
        - "Other"
      default: 0
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context and Environment
      description: Provide context about your setup if relevant
      placeholder: |
        - OS: [e.g. macOS 14.0, Ubuntu 22.04, Windows 11]
        - App version: [e.g. v1.0.0]
        - What you're trying to achieve
        - Any relevant configuration

  - type: textarea
    id: attempted
    attributes:
      label: What You've Tried
      description: What have you already tried to solve this?
      placeholder: |
        - Steps you've already taken
        - Documentation you've consulted
        - Commands you've run

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and documentation
          required: true
        - label: I have provided sufficient context
          required: true